# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7f23f1a81eeed93fbd531dcfb315aab40158c127e8979a72168b2b4edc8e81c6a76d77b86a6364503537acf3f2b380531133f9251703cc43251de6a86cc6502

test:
  secret_key_base: 559b79b114bf10620f98ce2fcfc6383aca865ba5fbe15444a8005b0e01fd937401a30c72c43766a8666b45bde504c7cf9664af0c63aa54d1d14575bd2a71dda2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
